#!/usr/bin/env python3
"""Shared feature schema for long-horizon predictor analytics."""

LONG_TERM_FEATURE_NAMES = [
    "current_power_w",
    "power_lag_5",
    "power_lag_60",
    "power_roll_mean_10",
    "power_roll_mean_60",
    "power_roll_std_60",
    "power_roll_mean_300",
    "ambient_temp_c",
    "ambient_humidity_pct",
    "system_supply_v",
    "time_hour_sin",
    "time_hour_cos",
    "system_weekday_sin",
    "system_weekday_cos",
    "system_weekend_flag",
    "system_bank_holiday_flag",
    "system_current_energy_window_wh",
    "system_tariff_rate_per_kwh",
    "process_state_code",
    "process_progress_ratio",
    "process_cycle_count",
    "process_tank1_level_pct",
    "process_tank2_level_pct",
    "process_tank1_temp_c",
    "process_tank2_temp_c",
    "load_on_count",
    "load_duty_sum_all",
    "load_fault_active_count",
    "load_fault_latched_count",
    "load_on_critical",
    "load_on_essential",
    "load_on_important",
    "load_on_secondary",
    "load_on_non_essential",
    "load_motor1_on_ratio",
    "load_motor2_on_ratio",
    "load_heater1_on_ratio",
    "load_heater2_on_ratio",
    "load_lighting1_on_ratio",
    "load_lighting2_on_ratio",
]
